### ISSUE TITLE
Granular Volume Control in Playback Mode

### ISSUE THREAD

**Issue by Realitycrafter** [andreasjhkarlsson/mac-dial#1]
The ability to use granular volume control ala holding option+shift and using volume keys.

**Comment by andreasjhkarlsson** [comment]
Implemented in [version 1.2](https://github.com/andreasjhkarlsson/mac-dial/releases/tag/releases%2F1.2). :)

**Comment by Realitycrafter** [comment]
Very nice.  Thank you!
