### ISSUE TITLE
Choose media player

### ISSUE THREAD

**Issue by MacSpikes** [andreasjhkarlsson/mac-dial#10]
On my MacBook Pro (silicon), the dial volume does what it should do. When the Qobuz (a streaming service like Tidal) media player is active, the button can pause/start a song and double clicking skips to the next song. On my MacMini (silicon) however, the volume controls work the same, but pressing the button always opens Apple Music and will not control another media app that is active. Would it be possible to assign a default media app?

**Comment by ikeyvan** [comment]
Hi,

Did you try with another app or using the media buttons on your keyboard?

My intuition here, having worked on Deezer’s desktop app, is that it might be Qobuz app that doesn’t register correctly the fact that it’s playing media with macOS.

In that case the problem would come from the Qobuz app, not macdial.

**Comment by MacSpikes** [comment]
Hi and thanks for replying. Every media app I try does not respond and all that happens when pressing the dial is that Apple Music opens. System volume works as expected however.

**Comment by MacSpikes** [comment]
Got it: under System Preferences -> Security & Privacy -> Privacy -> Accessibility I needed to add "Qobuz" to allow to control my computer. Problem solved it seems!
