### ISSUE TITLE
I get this error when I attempt to build in Xcode. what am I doing wrong?

### ISSUE THREAD

**Issue by rkasha** [andreasjhkarlsson/mac-dial#13]
ld: warning: directory not found for option '-L/Users/daddy/Documents/GitHub/mac-dial/lib/hidapi/build/src/mac'
ld: library not found for -lhidapi
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by andreasjhkarlsson** [comment]
Hi!

Did you follow the instructions on how to build in the README?

**Comment by andreasjhkarlsson** [comment]
Closed due to inactivity.
