### ISSUE TITLE
Suggestion: Reverse the wheel and keybind on click

### ISSUE THREAD

**Issue by kflore16** [andreasjhkarlsson/mac-dial#2]
I don't know if its possible but if the ability to reverse the wheel functionality or even setting a keybind on click. Awesome project by the way, I've been using it for days now.

**Comment by ShadyNawaraNexplore** [comment]
Fyi, i created a pr that adds an option to change scroll direction. #9

**Comment by andreasjhkarlsson** [comment]
Closing this issue for now as your PR has been merged and key bind is out of scope for this project currently (best solved by a custom fork at this point).
