### ISSUE TITLE
Double Click Issue in Playback Mode

### ISSUE THREAD

**Issue by brikuth** [andreasjhkarlsson/mac-dial#4]
Such a luxurious feeling using the dial for volume. Though I'm finding that when I double press in playback mode, instead of progressing to the next track as expected, it first pauses the music and then progresses to the next song (leaving it in a stopped state) -  Using Apple music on OS X 12.0.1

**Comment by brikuth** [comment]
Another cool feature would be to switch between scroll and playback mode with a press of the button push.

**Comment by andreasjhkarlsson** [comment]
Fixed in latest release!

**Comment by brikuth** [comment]
Thank you very much for the work you put into making this work so well.
How can I send you a donation?
