### ISSUE TITLE
use dial controls the slide

### ISSUE THREAD

**Issue by xusongpei** [andreasjhkarlsson/mac-dial#7]
Maybe it is a stupid question. I want to use the dial to control a slide that I had built in a webapp by python on my Mac, what should I do? Do I need to change something in the code? Or if I want to use python to read the value of the rotation of the dial, how should I do it? I had never used swift before, so I am a little bit confused. Thank you

**Comment by andreasjhkarlsson** [comment]
Hi and thanks for the interest in this project. Closing this issue as it's not really a work item for this repository.

To give you some hint on how to achieve your goal: I would probably see if I could use hidapi (the library this app uses to communicate with the dial) directly from python or find some other library for python that can read Bluetooth HID). Good luck!
