### ISSUE TITLE
cannot find xxx in scope

### ISSUE THREAD

**Issue by xusongpei** [andreasjhkarlsson/mac-dial#8]
Why it gives me such error: cannot find 'hid_get_manufacturer_string' in scope, and also 'hid_get_serial_number_string', 'hid_close', 'hid_open' etc.?

**Comment by andreasjhkarlsson** [comment]
Sounds like you didn't clone the hidapi submodule. Try $ git submodule update --init and then run build_hidapi.sh before building from xcode.
